### ISSUE TITLE
Suspect of malformed URL in "ImageActionExample"

### ISSUE THREAD

**Issue by franz0272** [vishalmysore/simplelam#2]
Hi.
I've been trying for days to execute "ImageActionExample", but I always obtain the following error:

Exception in thread "main" com.t4a.processor.AIProcessingException: com.google.api.gax.rpc.PermissionDeniedException: io.grpc.StatusRuntimeException: PERMISSION_DENIED: Permission 'aiplatform.endpoints.predict' denied on resource '//aiplatform.googleapis.com/projects/MYPROJECT/locations/europe-west8/publishers/google/models/gemini-1.0-pro-vision-001' (or it may not exist).
        at com.t4a.processor.GeminiImageActionProcessor.imageToText(GeminiImageActionProcessor.java:124)
        at org.example.image.ImageActionExample.main(ImageActionExample.java:26)
Caused by: com.google.api.gax.rpc.PermissionDeniedException: io.grpc.StatusRuntimeException: PERMISSION_DENIED: Permission 'aiplatform.endpoints.predict' denied on resource '//aiplatform.googleapis.com/projects/MYPROJECT/locations/europe-west8/publishers/google/models/gemini-1.0-pro-vision-001' (or it may not exist).

My suspect is that the URL is not well formed, since " **v1/** projects " should be, in my opinion, the right path to point to.

What am I doing wrong?

Thank you so much,
Franz

**Comment by vishalmysore** [comment]
hey this seems permission issue on your google cloud setup , can you please look into this thread https://www.googlecloudcommunity.com/gc/AI-ML/text-bison-001-IAM-PERMISSION-DENIED/m-p/602198

**Comment by franz0272** [comment]
I can not manage the issue. I tried to configure what you suggest, but the problem persists... Any idea, pls?
Thanks

**Comment by franz0272** [comment]
Working, now! Thanks!!!!!
